### PR TITLE
[Work In Progress] Major update 1.14

### PR DESCRIPTION
**Pull request by ltbam**
### Description

 
Goal:

### CODE REVIEW

**Comment by All4Gis** [comment]
Please use the branch major_update_1_14

**Comment by All4Gis** [comment]
Can you check the branch?in my case everything works slower, the video, the magnifier etc

**Comment by ltbam** [comment]
Hello Francisco, 

I did some more other fixes and optimisations, on Kadas Albireo it runs now fine and has been accepted from our client.

As I see the magnifier works when you make a click, not with mouseover. Was it intended to use mouseouver ?

Regards,

Rémy

**Comment by All4Gis** [comment]
the magnifier works with the mouseover, but in this branch works with click, I remember.You can see the master branch

**Comment by PedroVenancio** [comment]
Hi @ltbam and @All4Gis 

I'm testing this branch (major_update) and I'm seeing an issue.

When I open one video, it seems to work fine, saving the first footprint in "Footprint" temporary layer.

However, if then I open another video, the player starts ok, but when I click, for instance, to pause, the footprint and trajectory points to the first video footprint, because that info is still in the "Footprint" temporary layer.

Please take a look at this screencast:

https://cld.pt/dl/download/b6d8875f-9dd6-44f7-914d-efae02fecdd5/QGIS_FMV_major_update.mp4 

Can you confirm?

**Comment by All4Gis** [comment]
fixed some changes, but tracking and censure tool not work in this branch @ltbam

**Comment by All4Gis** [comment]
> Hi @ltbam and @All4Gis
> 
> I'm testing this branch (major_update) and I'm seeing an issue.
> 
> When I open one video, it seems to work fine, saving the first footprint in "Footprint" temporary layer.
> 
> However, if then I open another video, the player starts ok, but when I click, for instance, to pause, the footprint and trajectory points to the first video footprint, because that info is still in the "Footprint" temporary layer.
> 
> Please take a look at this screencast:
> 
> https://cld.pt/dl/download/b6d8875f-9dd6-44f7-914d-efae02fecdd5/QGIS_FMV_major_update.mp4
> 
> Can you confirm?
> 
> I need to restart QGIS to get it working again. Removing the videos or the temporary layers doesn't solve.

You are right,We need fix this new issue

**Pull request merged**
