### PR TITLE
RTP Streaming with Splitter

### PR DESCRIPTION
**Pull request by ltbam**
### Description
This PR enables RTP streaming with QGISFMV.  
 
Goal:
The splitter is necessary because if the stream is directly passed to QtMediaPlayer, there is no way to catch the metadata from QtMediaPlayer class.

How to Test:

1) Setup a RTP source stream with FFMPEG on a local video file:
ffmpeg.exe -fflags +genpts -stream_loop -1 -re -i "C:\temp\myVideoFile.TS" -f rtp_mpegts -c copy -map 0:v -map 0:a -map 0:d rtp://127.0.0.1:8888

2) Open QGISFMV and select menu "Open Stream", enter host:127.0.0.1 and port:8888

How it works:
QGISFMV will start a splitter that will read the source port 8888, forward the A+V to port 8898 (For QtMultimedia) and send the Metadata to stdout. There is a reader that puts the metadata into a Queue, later used by the metadata decoder.

### CODE REVIEW

**Comment by All4Gis** [comment]
I can't see the video, I only see a black screen! I'm going to work on this PR to try to fix it.

**Comment by All4Gis** [comment]
I can't meger this PR, since I can't get it to work for me.
Can you try the changes I've uploaded?On the other hand I don't understand this part:

```
            if self.isStreaming:
                # show video from splitter (port +1)
                oldPort = videoPath.split(":")[2]
                newPort = str(int(oldPort) + 10)
                url = QUrl(videoPath.replace(oldPort, newPort))
```
Why do you change the port here?

I have tried with an example always and if it works but not in the plugin.

Can you try on another computer? Perform a more robust test to make it work much better?
[qt5_player.zip](https://github.com/All4Gis/QGISFMV/files/3828728/qt5_player.zip)

**Comment by ltbam** [comment]
If you dont change AV Port and directly read the source stream with QtMultimedia, won't have any chance to read the metadata. That's why we forward AV to another port (+10) so that QtMultimedia can open it.
I will try on another laptop.

**Comment by ltbam** [comment]
In QGisFmvUtils line 201: There as a dealock with the proposed changes:

self.p = subprocess.Popen(self.cmds, startupinfo=startupinfo, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE)
# DONT USE  _spawn here as it will DeadLock, and the splitter won't start
#self.p = _spawn(self.cmds)

**Comment by ltbam** [comment]
I also found another potential problem with the player at QgisFmvPlayer def closeEvent(self, event):
**self.parent._PlayerDlg = None**
#Potential problem. If we create a new Player with the same stream
#address and port, it will certainly be blocked on the port.

**Comment by ltbam** [comment]
Please @All4Gis test again, I have fixed an issue with the player and a deadlock with the splitter.

I tried on a new PC and it did not work with the LavFilters only, I needed to install K-Lite Codec pack:
https://codecguide.com/download_k-lite_codec_pack_basic.htm

**Comment by All4Gis** [comment]
Good job @ltbam I'll try it later.

**Comment by All4Gis** [comment]
There is a mistake! If we close the dialog and reopen player, ask again for the layers 
**If you close or reopen the video all the information will be erased. ..**.

**Comment by All4Gis** [comment]
I've made some changes to avoid the closing dialog and to be able to change the video.

But there is a bug. The steps to reproduce it are:

1. Open rtp connection and it shows well
2. Close the player
3. Open a video that we have as a .ts,

The metadata shown are those of rtp

**Comment by ltbam** [comment]
Good catch! 
Now we use the same player object we need to set the new meta_reader to it. I fixed this problem.

I also made a small change in the Layer group:
If you have a preloaded project with a basemap for instance, the group will draw on top of the basemap, not bellow.

**Comment by All4Gis** [comment]
Perfect, but we have to solve the problem that the video isn't always seen.Using the sample video, maybe we can fixed

**Comment by All4Gis** [comment]
I'm going to merge it and put it down as experimental

**Pull request merged**
